### ISSUE TITLE
Inquiry About the Release of Training Code

### ISSUE THREAD

**Issue by EchoForger** [jwliao1209/DiffQRCode#1]
I really appreciate your DiffQRCode project and find it very innovative. However, I noticed that the training code for the model has not been open-sourced yet. Could you please share when you expect to release this part of the code? Many of us are eager to use it for further research and applications.

Thank you for your work, and I hope to see updates soon!

**Comment by jwliao1209** [comment]
We are refactoring our pipeline right now and will release our code soon.

**Comment by LucaCappelletti94** [comment]
Any updates?
